apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80  # Expose the service on this port
      targetPort: 8501  # Forward traffic to this container port
  type: LoadBalancer  # Use NodePort for external access
